---
# tasks file for c1.fail2ban
- name: Install fail2ban
  apt: name=fail2ban state=present
  when: fail2ban_enabled
- name: Add fail2ban system user
  user: name=fail2ban comment="Fail2ban User" group=adm createhome=no system=yes
  notify: restart fail2ban
- name: "Configure /etc/default/fail2ban"
  lineinfile: dest=/etc/default/fail2ban
              regexp="^FAIL2BAN_USER"
              line='FAIL2BAN_USER="fail2ban"'
              state=present
  notify: restart fail2ban
- name: Create /etc/fail2ban/fail2ban.local from template
  template:
    src: "fail2ban.local.j2"
    dest: "/etc/fail2ban/fail2ban.local"
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
- name: Create /etc/fail2ban/jail.local from template
  template:
    src: "jail.local.j2"
    dest: "/etc/fail2ban/jail.local"
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
- name: fix permissions on logfile
  when: fail2ban_logtarget.startswith("/")
  file: name="{{ fail2ban_logtarget }}" state=file group=adm mode=0664
